export const playerData = {
  tier1s: [
    { ign: "HabibiHadron", rank: "high", country: "pk" },
    { ign: "HabibiBread", rank: "high", country: "pk" },
    { ign: "HabibiJod", rank: "low", country: "pk" },
    { ign: "YTMee", rank: "low", country: "pk" },
  ],
  tier2s: [
    { ign: "Kyssta", rank: "high", country: "pk" },
    { ign: "rtxw", rank: "low", country: "pk" },
    { ign: "Yeti", rank: "low", country: "in" },
  ],
  tier3s: [
    { ign: "R3hmanXD", rank: "high", country: "pk" },
    { ign: "PookieMall", rank: "high", country: "in" },
    { ign: "xThunder_", rank: "high", country: "in" },
    { ign: "GeneralAsimMunir", rank: "low", country: "pk" },
    { ign: "YTMee", rank: "low", country: "pk" },
    { ign: "Duazy", rank: "low", country: "in" },
    { ign: "Nigger", rank: "low", country: "pk" },
  ],
  tier4s: [
    { ign: "GeneralAsimMunir", rank: "high", country: "pk" },
    { ign: "DrPuuuu", rank: "high", country: "pk" },
    { ign: "Starzide", rank: "high", country: "pk" },
    { ign: "INDIANGODENDER", rank: "high", country: "pk" },
    { ign: "ghunaim", rank: "high", country: "pk" },
    { ign: "5cei", rank: "high", country: "pk" },
    { ign: "xKyoi", rank: "high", country: "pk" },
    { ign: "Kylaz", rank: "low", country: "pk" },
    { ign: "g", rank: "low", country: "pk" },
    { ign: "h", rank: "low", country: "pk" },
    { ign: "i", rank: "low", country: "pk" },
    { ign: "j", rank: "low", country: "pk" },
    { ign: "k", rank: "low", country: "pk" },
    { ign: "ll", rank: "low", country: "pk" },
    { ign: "m", rank: "low", country: "pk" },
    { ign: "n", rank: "low", country: "pk" },
    { ign: "o", rank: "low", country: "pk" },
  ],
  tier5s: [
    { ign: "xUltimate_", rank: "high", country: "pk" },
    { ign: "Kyssta", rank: "high", country: "pk" },
    { ign: "Boltness", rank: "high", country: "pk" },
  ],
};
