export const playerData = {
  tier1s: [
    { ign: "HabibiHadron", rank: "high", country: "pk" },
    { ign: "HabibiBread", rank: "high", country: "pk" },
    { ign: "HabibiJod", rank: "low", country: "pk" },
    { ign: "YTMee", rank: "low", country: "pk" },
  ],
  tier2s: [
    { ign: "Kyssta", rank: "high", country: "pk" },
    { ign: "rtxw", rank: "low", country: "pk" },
    { ign: "Yeti", rank: "low", country: "in" },
  ],
  tier3s: [
    { ign: "R3hmanXD", rank: "high", country: "pk" },
    { ign: "PookieMall", rank: "high", country: "in" },
    { ign: "xThunder_", rank: "high", country: "in" },
    { ign: "GeneralAsimMunir", rank: "low", country: "pk" },
    { ign: "YTMee", rank: "low", country: "pk" },
    { ign: "Duazy", rank: "low", country: "in" },
    { ign: "Nigger", rank: "low", country: "pk" },
  ],
  tier4s: [
    { ign: "GeneralAsimMunir", rank: "high", country: "pk" },
    { ign: "DrPuuuu", rank: "high", country: "pk" },
    { ign: "a", rank: "high", country: "pk" },
    { ign: "b", rank: "high", country: "pk" },
    { ign: "c", rank: "high", country: "pk" },
    { ign: "d", rank: "high", country: "pk" },
    { ign: "e", rank: "high", country: "pk" },
    { ign: "f", rank: "high", country: "pk" },
    { ign: "g", rank: "high", country: "pk" },
    { ign: "h", rank: "high", country: "pk" },
    { ign: "i", rank: "high", country: "pk" },
    { ign: "j", rank: "high", country: "pk" },
    { ign: "k", rank: "high", country: "pk" },
    { ign: "ll", rank: "high", country: "pk" },
    { ign: "m", rank: "high", country: "pk" },
    { ign: "n", rank: "high", country: "pk" },
    { ign: "o", rank: "high", country: "pk" },
  ],
  tier5s: [
    { ign: "xUltimate_", rank: "high", country: "pk" },
    { ign: "Kyssta", rank: "high", country: "pk" },
    { ign: "Boltness", rank: "high", country: "pk" },
  ],
};
